version: 2.1

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure backend infrastructure exist
          command: aws cloudformation create-stack --stack-name my-stack --template-body file://template.yml --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM" --region=ap-northeast-1

workflows:
  my_workflow:
    jobs:
      - create_infrastructure