version: 2.1

jobs:
  job_failure:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: return 1
      - run:
          name: Upload Failed Tests
          command: echo "Hello Error!"
          when: on_fail

workflows:
  my_workflow:
    jobs:
      - job_failure