version: 2.1

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
        auth:
          AWS_ACCESS_KEY_ID: AKIA5LW4I6ERTHLFDDBP
          AWS_SECRET_ACCESS_KEY: 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
          AWS_DEFAULT_REGION: ap-northeast-1
    steps:
      - checkout
      - run:
          name: Ensure backend infrastructure exist
          command: aws cloudformation create-stack --stack-name my-stack --template-body template.yml --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM" --region=ap-northeast-1

workflows:
  deploy:
    jobs:
      - create_infrastructure